# Generated by Django 2.0b1 on 2017-11-24 09:46

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_title', models.CharField(max_length=128)),
                ('mes_text', models.TextField(max_length=342)),
                ('mes_created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mes_public_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'HomeTable',
            },
        ),
    ]
